# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
        
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      run: |
        curl -sSf https://rye-up.com/get | bash 
        echo 'source "$HOME/.rye/env"' >> ~/.bashrc
        rye pin cpython@3.11
    - name: Install dependencies
      run: |
        rye sync
    - name: Lint with ruff
      run: |
        ruff check pygam
      
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - uses: codecov/codecov-action@v3
    - name: Set up Python ${{ matrix.python-version }}
      run: |
        curl -sSf https://rye-up.com/get | bash 
        echo 'source "$HOME/.rye/env"' >> ~/.bashrc
        rye pin cpython@${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        rye sync
    - name: Test with pytest
      run: |
        python3 -m pytest --cov=pygam
        python3 -m codecov
